### PR TITLE
Sanitize the URL array before processing (Fix #33 [part 2]) and Mocha tests

### LINKED ISSUE #33: Error when using multiple download with list.txt
So, I've tried the new functionality for downloading a whole bunch of videos from a text file.
I've put the urls in the text file, one url per each line like it says on the instruction of readme.

I launched this:
`node destreamer.js --username MYUSERNAME --outputdirectory "videos" \ --videoUrls list.txt`

(Also tried using the correct escape character for powershell, same result), I get this:

```
Video URLs: [ 'list.txt' ]
Username: MYUSERNAME
Output Directory: videos
Video/Audio Quality: undefined
Using youtube-dl version 2020.03.08
Using ffmpeg version git-2020-03-15-c467328 Copyright (c) 2000-2020 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
We are logged in.
Got cookie. Consuming cookie...
Calling Microsoft Stream API...
ApiGatewayUri: https://euwe-1.api.microsoftstream.com/api/
ApiGatewayVersion: 1.3-private
Fetching title and HLS URL...
Error when calling Microsoft Stream API: 400 undefined400
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
```

And chromium crash, not even downloading the first video.
It seems an error calling microsoft stream API.. is it a bug?

### PR DESCRIPTION
**Pull request by kylon**
This will skip empty lines and invalid urls such as:

(video not found)
```
https://*/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd&
https://*/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddd
```

while these are valid:
```
https://*/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd?
https://*/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd?(queries)
*/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd
```

mocha tests:
As clean as possible.

### CODE REVIEW

File: test/test.ts [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+            "https://web.microsoftstream.com/video/xxxxxx-zzzz-hhhh-rrrr-dddddddddddd",
+            ""
+        ];
+        const expectedOut: string[] = [
+            "https://web.microsoftstream.com/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd",
+            "https://web.microsoftstream.com/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd",
+            "https://web.microsoftstream.com/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd?a=b&c",
+            "https://web.microsoftstream.com/video/xxxxxxxx-zzzz-hhhh-rrrr-dddddddddddd?a"
+        ];
+        const tmpFile = tmp.fileSync({ postfix: '.txt' });
```
Comment (snobu) [inline test/test.ts:51]: Not familiar with the `tmp` module, what happens if our test fails midway through or gets cancelled (CTRL-C)? Are we leaving the temporary .txt file behind?

Comment (kylon) [reply test/test.ts:51]: According to the docs if you don't explicitly tell tmp to keep the file, the temp file will be "closed and unlinked on process exit".
Also this is using the default OS temp dir, no file is being created on our directory :)

Comment (snobu) [reply test/test.ts:51]: That was my concern that we're accidentally leaving garbage behind outside our working folder. Let's merge it like this, worry later :) Thanks again!
